services:
  # Tier 3: Base de Datos (PostgreSQL)
  database:
    image: postgres:18
    container_name: limpieza_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=limpieza_empresas
    volumes:
      # Guardamos los datos en una carpeta 'postgres_data' para que persistan
      - ./postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5



  # Tier 2: Backend (Lógica de Negocio)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: limpieza_backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:admin@database:5432/limpieza_empresas
    volumes:
      - ./backend:/app
      - ./database:/app/database
    depends_on:
        database:
          condition: service_healthy
    networks:
      - app-network
    command: python run.py

  # Tier 1: Frontend (Presentación)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: limpieza_frontend
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    command: npm start

networks:
  app-network:
    driver: bridge


